build:
  environment:
    php: '7.3'
    
  tests:
    override:
      -
        command: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml ./test
        coverage:
          file: build/logs/clover.xml
          format: clover

checks:
    php:
        code_rating: true
        duplication: true
