environment:
  php: '7.1'
    postgresql: false
    mongodb: false
    redis: false
    memcached: true
    neo4j: false
    rabbitmq: false
        
checks:
  php: true
    
filter:
  excluded_paths:
    - test/*
        
tests:
  override:
    - phpcs-run --runtime-set ignore_warnings_on_exit 1 --standard=psr2 src
