language: php
sudo: false


matrix:
  fast_finish: true
  include:
      env: BLACKFIRE=on
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
    - php: nightly

cache:
    - $HOME/.composer/cache/files

before_install:
    - |
        if [[ "$BLACKFIRE" = "on" ]]; then
            openssl aes-256-cbc -K $encrypted_504296c3bd2c_key -iv $encrypted_504296c3bd2c_iv -in .blackfire.travis.ini.enc -out ~/.blackfire.ini -d
            curl -L https://blackfire.io/api/v1/releases/agent/linux/amd64 | tar zxpf -
            chmod 755 agent && ./agent --config=~/.blackfire.ini --socket=unix:///tmp/blackfire.sock &
        fi

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

install:

  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

before_script:
    - phpenv config-rm xdebug.ini || true
    - |
        if [[ "$BLACKFIRE" = "on" ]]; then
            curl -L https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$(phpenv version-name | tr -d '.')-zts | tar zxpf -
            echo "extension=$(pwd)/$(ls blackfire-*.so | tr -d '[[:space:]]')" > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/blackfire.ini
            echo "blackfire.agent_socket=unix:///tmp/blackfire.sock" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/blackfire.ini
        fi

script:
  - ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --standard=psr2 src
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml ./test

after_script:
  - travis_retry php vendor/bin/coveralls -v
