language: php

jobs:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install --no-interaction --no-progress --no-suggest

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1
  - SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1 ./vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml ./test

after_script:
  - travis_retry php vendor/bin/coveralls -v
